### ISSUE TITLE
emit events

### ISSUE THREAD

**Issue by isaacs** [npm/arborist#24]
- [ ] make a list of what kinds of events we care about
- [ ] Emit events when that stuff happens
- [ ] should enable timing and logging in npm/cli

**Comment by claudiahdz** [comment]
For further discussion:

_Make a list of what kinds of events we care about:_

### High level Events:
- loading virtual tree
- loading actual tree
- building ideal tree
- updating node (permanent)
- replacing node (temporary)
- reifying starts
- reifying finishes
- prunning
- deduping
- updating shrinkwrap
- errors

_**How much into detail do we want to go?**_
- loadVirtual: resolving links..
- idealTree: adding/removing deps, fetching manifest, creating new node, checking placement of node, placing node...
- reifying: diffing, retiring shallow nodes, create leaf nodes...

**_Do we want to log(print) the actual tree as the scripts? Perhaps for `--loglevel=silly`?_**
Not sure this is arborist or the CLI's job (I mean the "prettifying" of the tree, saw some utility functions under the scripts in arborist).

My thoughts are probably a bit disordered, but just wanted to start the conversation.

**Comment by isaacs** [comment]
I think printing/prettifying the tree is probably out of scope for what Arborist should log.  We'll pass the tree to the cli, and it can pretty-print the tree or a breakdown there, somewhat like it currently does, though that output could probably be improved.  Same for `npm ls` -- it'll just call `readActual()` and then pretty it up.  The printing in `scripts/` is mostly for debugging Arborist itself.

I think a good first pass would be to look at what the cli currently does, and use that as a guide.  It gets us very entangled with `npmlog` and `guage`, but as mentioned in slack, getting off of those is probably best done as a separate project anyway, since so many of our other deps have the same entanglement.

**Comment by claudiahdz** [comment]
OK, I made a list according to what the CLI does right now during installation and the relevance with arborist:

- loadActualTree
- loadVirtualTree
- buildIdealTree
- runPreinstallTopLevelLifecycles
- runPostinstallTopLevelLifecycles
- loadDeps
- moveDep
- removeDep
- initReifying
- finishReifying
- loadShrinkwrap
- removeExtraneousNodes
- fetchManifest
- diff-trees
- resolveLinks

The CLI also seems to log everytime a node is moved around the tree. Do we also want to log that?

On the CLI we differentiate between events related to installation/uninstalling/upgrading, etc. It doesn't make much sense to do this on arborist, isn't? Since the adding/removing/change of nodes will all be handle by a single library.

Does it make sense to end up with something like: `logger.silly('arborist', 'loadActualTree')` ?

**Comment by isaacs** [comment]
Yeah, there's necessarily going to be some changes to the specifics of what we log, since the specifics of what we're _doing_ have changed.

For example, we don't really "move" deps, so that log line seems weird.

Probably I'd start by creating log tracker blocks like the CLI does currently for the top-level functions in Arborist.reify and Arborist.buildIdealTree, and use the queue length in `buildIdealTree` as a source for guage, and probably add some kind of counter to track how many `_reifyNode` calls we have in place in reify.js and throw that at guage as well, so we have a progress bar that tracks the progress.
