### ISSUE TITLE
[QUESTION] Isn't this deduplication happening too late in audit?

### ISSUE THREAD

**Issue by naugtur** [npm/arborist#288]
# What / Why

https://github.com/npm/arborist/blob/main/lib/audit-report.js#L130 uses a `Set` to deduplicate a result of a bunch of promises. 
The actual async thing behind those is fetching packuments. If deduplication is necessary here at all, wouldn't it be better to deduplicate earlier?

I expect to get "there's a cache" in response, but these are spawned in parallel and it's likely all/most of the requests start before any of them finishes so the cache gets populated many times but not used.  
It'd have to store promises in cache immediately after the call instead of the resulting values to make the cache suffice.

## Where
https://github.com/npm/arborist/blob/main/lib/audit-report.js#L130

## Who
@isaacs 

Possible solution - reindex the references in the double for loop and `Promise.all(reindexed.map(...))`

Feel free to ignore&close if I'm missing something obvious. ;)

**Comment by isaacs** [comment]
That's just the initial set.  The deduplication that's relevant here is preventing us from iterating over the same item again in subsequent iterations.

Consider this simplified version of the pattern:

```js
const threeXPlus1 = x => x % 2 ? (3 * x + 1) : (x / 2)

const results = new Map()

const initial = []
for (let i = 1; i < 100; i++)
  initial.push(i)
const set = new Set(initial)

for (const x of set) {
  const result = threeXPlus1(x)
  set.add(result)
  results.set(x, result)
}

console.log(results)
```

When we get to `8`, and the result is `4`, we add `4` to the set.  But since `4` is already in the set, the `set.add(4)` is a no-op, and we don't traverse it a second time.

If it was just pushing into an array, it would loop forever, so this pattern is useful in cases where you have some set of items to iterate over, which may expand in the process, but which will eventually converge down to a finite set.

(Sidenote: it's never been proven, and might not be possible to prove, whether 3x+1 is actually such a set that will be guaranteed to converge for all natural numbers, and it is widely regarded as a cursed problem in mathematics, which confounds any attempt to formalize it, and has taken years off of many mathematicians' careers.)

**Comment by naugtur** [comment]
Appreciate the use of the cursed sequence :) 

I meant more on the async flow of things, to deduplicate before adding to promises array, because .calculate may be called many times for the same thing but I see how that's not significant enough to be concerned.
