### ISSUE TITLE
[BUG] arborist does not create bin links for packages with `directories.bin`.

### ISSUE THREAD

**Issue by everett1992** [npm/arborist#296]
# What / Why
arborist v2.6.3 and npm v7.18.1 do not create bin links for packages with `directories.bin`. npm v6 does. 

## When
I initially encountered this bug in a private registry, and in the registry I saw the issue when using npm v7 and upgrading lockfile version 1 lockfile. When installing from the registry without a lockfile npm v7 does create the correct links. However I was not able to reproduce that with npmjs.com (sshpk@1.16.1 has directories.bin but with or without a lockfile v7 installs the correct links).

I am able to reproduce the issue with a file tar dependency. 

### Current Behavior
When installing a tgz dependency npm will install all packages and create bin links for `package.json#bin` but it will not create any bin links for `package.json#directories.bin`.

### Steps to Reproduce

1. Download sshpk@1.16.1 from npm
```
$ curl -O $(npm info sshpk@1.16.1 dist.tarball)
$ npx pacote manifest sshpk-1.16.1.tgz --json | jq '{directories, bin}'
{
  "directories": {
    "bin": "./bin",
    "lib": "./lib",
    "man": "./man/man1"
  },
  "bin": null
}
```
3. create a package using our sshpk-1.16.1.tgz package
```
$ echo '{"name":"consumer","version":"1.0.0","dependencies":{"sshpk":"file:sshpk-1.16.1.tgz"}}' > package.json
```

4. reify the package (Or `npm install` with v7 has the same result)
```
$ npx @npmcli/arborist@2.6.3 reify
```

4. check that `node_modules/.bin/example` exists
```
$ ls node_modules/.bin
ls: cannot access 'node_modules/.bin': No such file or directory
```

### Expected Behavior
npm v7 / arborist should respect the directories.bin field. It is [documented](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#directoriesbin) and supported by v6.

**Comment by everett1992** [comment]
In my initial debugging, against the private registry, I found this

https://github.com/npm/arborist/blob/114b09d4b8bb182281406af4183b10913534393e/lib/arborist/rebuild.js#L210-L224

When I was upgrading from v1 lockfile 
 - _oldMeta would be true so arborist reads package.json from disk
 - node.package has dev, dependencies, version, and name defined, but scripts and bin are undefined.
 - read-package-json-fast does not normalize directories.bin to bin.
  - arborist updates node.package.script but it doesn't update node.package.bin

**Comment by isaacs** [comment]
Hm, this is trickier than it looks at first glance.  We have some options that merit discussion, I think.  I agree that the current scenario is not great, because the docs and the program don't agree.

Yes, we no longer walk the `directories.bin` and assemble a `bin` object for you when reading the package.json from disk.  However, this _is_ still done by the (significantly slower) package.json reading that is done for publish.

Options:

1. Make `read-package-json-fast` read the `directories.bin` if defined, and create a `bin` object, like `read-package-json` did.  This restores the functionality that npm v6 had, and which is documented for npm v7.
2. Remove the `directories.bin` handling from `read-package-json` (the slow one), and remove it from the docs, and basically call this a breaking change that we unfortunately forgot to update the docs for.

(1) has the potential impact of making package.json loading from disk slower, which is a pretty significant hit when reading a `node_modules` tree of thousands of package.json files.  But, it is the (imo, reasonable) user expectation, and perf is mitigated by the fact that we are only going to do this if a `directories.bin` is defined, and a `bin` is not.

(2) would be less work, and retains maximum performance, but will probably come as a surprise to anyone using `directories.bin` today (which _sort of_ works today, because the published manifest _does_ have a fully realized `bin` object!)

Perhaps an option (3) would be to do (1), but deprecate the behavior, both in `read-package-json`, so that publishers know to stop relying on it.  However, in my experience, such warnings generally are ignored until they start breaking things, and I'm hesitant to add noise that we know will be ignored, because it trains people to ignore more important warnings.

**Comment by isaacs** [comment]
Nevermind. Had the discussion, we're going with (1).  Will be fixed by https://github.com/npm/read-package-json-fast/pull/4

**Comment by everett1992** [comment]
>  However, this is still done by the (significantly slower) package.json reading that is done for publish.

- Does npm normalize package.json before publishing, or does the registry server normalize the packument?
- Is the package.json in the tarball normalized?
-  Should npm pack normalize the package.json included in the tarball?
