### ISSUE TITLE
How can I get the effect of `npm ls --production`?

### ISSUE THREAD

**Issue by ljharb** [npm/arborist#40]
Using *each* of `loadActual`, `loadVirtual`, and `buildIdealTree` (since I use all three in what I'm building), how can i omit/ignore dev deps?

For `loadActual`, I can run `npm prune --production` first, and I get the tree I want; for `loadVirtual`, i'd presumably have to remove all lockfiles and run `npm install --package-lock-only --package-lock --production`; for `buildIdealTree`, it's not clear there's any way to work around it.

**Comment by wesleytodd** [comment]
So to document some of the conversation happening in the tools slack, I think that it would be awesome for these cases if there was a better mode to build tooling on top of `buildIdealTree` If there was a built in way to build an ideal tree from just a `package.json` and then inspect all the packages in the tree.  This use case is not very well served by the current implementation.

**Comment by isaacs** [comment]
You can always ignore the lockfile entirely in `buildIdealTree` and `reify` by passing in the option `{ update: {all: true}}`.  This builds the ideal tree using _only_ the package.json, re-evaluating all deps by hitting the registry for latest and greatest versions.

There are a few mechanisms for filtering dev nodes out of a tree.

Most general, least efficient:

```js
for (const node of tree.inventory.filter(node => !node.dev)) {
  // do something
}
```

This walks over every node in the tree, omitting those that have their `dev` flag set.

Most efficient, least general:

```js
for (const node of tree.children.values()) {
  if (node.dev)
    node.parent = null
}
doSomething(tree)
```

Since dev nodes only exist at the top level, or nested underneath other dev nodes, this removes all top-level dev nodes from the tree.  Of course, that actually mutates the tree, so it can be destructive if you then save the metadata files or reify the tree to disk, as it will remove dev nodes entirely.

Also, that does not work for _optional_ deps, which can exist at lower levels in the tree structure.  For that, you'd have to use `tree.inventory.filter(fn)`.

**Comment by isaacs** [comment]
If you want to walk the tree in a depth-first or breadth-first manner, rather than just hitting all nodes in an indefinite and arbitrary order, I recommend the [`treeverse`](http://npm.im/treeverse) module.

```js
const { breadth, depth } = require('treeverse')
depth({
  tree,
  getChildren: node => [...node.children.values()],
  filter: node => !node.dev,
  visit: node => doSomething(node),
})
```

**Comment by isaacs** [comment]
This kind of tree-walking mechanisms _may_ be slightly more efficient than `tree.inventory.filter()` for scanning optional deps, since an optional dep's child must be optional, so it avoids walking that part of the tree entirely.
